### ISSUE TITLE
Form builder: Dropdowns in tables can't be opened

### ISSUE THREAD

**Issue by JohnL17** [projectcaluma/ember-caluma#109]
The values of the dropdowns do not appear although the arrow change it's direction.

**Comment by czosel** [comment]
@fkm Is there really something to review here? This ticket is asking for a generic solution.

**Comment by fkm** [comment]
Not really. It's the z-index fix I committed in the project repository.

I just wanted mark it as not to-do and not complete. But thinking about it I might have to add some documentation to ember-caluma to mark this ticket as done/in-review.

**Comment by czosel** [comment]
We should probably think about how hard-linked `ember-caluma` is to specific UI libraries / UIkit in the first place.

**Comment by fkm** [comment]
Decoupling `ember-caluma` from predefined designs would be helpful. But in the name of efficiency I recommend we keep UIkit until we have completed the main business logic to avoid having to think about design during the development of core 'backend' features.

**Comment by czosel** [comment]
@JohnL17 Can you try to apply the fix documented in #142?
