### ISSUE TITLE
Meta reliant fields dont display chosen option

### ISSUE THREAD

**Issue by Yelinz** [projectcaluma/ember-caluma#139]
When the Widget Type selector is used and a different value is selected, the new value doesn't get displayed.

**Comment by Yelinz** [comment]
![help](https://user-images.githubusercontent.com/30687616/56346319-20010c00-61c2-11e9-92c2-9dd42aa45e91.gif)

Visualization of the problem

**Comment by czosel** [comment]
Awesome video! @fkm, do you want to tackle this?

**Comment by Yelinz** [comment]
The problem is with mirage delivering JSON strings instead of objects, it works with the caluma backend.
The field `hideLabel` on choice and choices questions are also affected by this now.
