### ISSUE TITLE
Make form accessible in JEXL expressions

### ISSUE THREAD

**Issue by czosel** [projectcaluma/ember-caluma#143]
If the same subform is used in multiple main forms, it would be handy to determine the "context" by exposing the form slug in the JEXL expressions. Like this, one can make a specific field hidden/required only in specific form contexts.

**Comment by czosel** [comment]
@kaldras What do you think?

**Comment by anehx** [comment]
I think @sliverc and me discussed this use case at the beginning of the project and decided not to do this since in this case it should actually be a different form. However, since we now have nested forms we should discuss this again..

**Comment by sliverc** [comment]
Is there an actual use case for this? I think as @anehx mentioned we left this out not to make JEXL too unpredictable and hard to maintain. One can argue that this is already the case... :smile:

**Comment by czosel** [comment]
We have the use case in one of our larger projects where we have multiple different form types which share the same form, but differ only in the `isRequired` setting on some questions. We could implement this by querying the form in the `isRequired` JEXL.

**Comment by sliverc** [comment]
I guess it is easy to implement on a JEXL level so why not if it helps. :+1:

**Comment by czosel** [comment]
Yeah, I guess we could just pass it as `context`.
