### ISSUE TITLE
Defaulting values with input

### ISSUE THREAD

**Issue by Yelinz** [projectcaluma/ember-caluma#151]
Values of placeholder and information text of all questions and options of choice/choices questions get a default value assigned, overwriting the given input.

![defaulting](https://user-images.githubusercontent.com/30687616/56559908-44366180-65a3-11e9-8c1a-1a499ca425a3.gif)

**Comment by czosel** [comment]
This is due to the way or Mirage Mock is set up. IMO, we should discuss finding another strategy for testing/mocking because the mirage mock has a whole class of issues.

Until then, I'd recommend testing with the actual backend.

**Comment by czosel** [comment]
The issue that right after creating a question it is not displayed ("No question found") also occurs with the actual backend though - this is something we should fix.

**Comment by Yelinz** [comment]
The problem is that I recorded it on https://caluma.io/ember-caluma/ and when someone is trying the form builder out and this happens most people would think it is broken.

**Comment by czosel** [comment]
Exactly, we just need to agree on how to proceed with the whole mirage story.
