### ISSUE TITLE
Replace ember-pikaday with ember-flatpickr

### ISSUE THREAD

**Issue by Yelinz** [projectcaluma/ember-caluma#1559]
ember-pickaday hasn't received a commit over a year and with the upcoming update to ember 4 it could cause some problems/ deprecation warnings. [ember-flatpickr](https://shipshapecode.github.io/ember-flatpickr/docs) also supports more inputs like date time and time, which would allow for those field types if they are ever needed.

**Comment by anehx** [comment]
Not necessary anymore, they picked up maintenance.
