### ISSUE TITLE
Form builder: Reopen of table not possible

### ISSUE THREAD

**Issue by JohnL17** [projectcaluma/ember-caluma#194]
When a table was closed without clicking on the save button, the table doesn't reopen if you click on the edit button.

**Comment by czosel** [comment]
@JohnL17 should be fixed by now, can you confirm?

**Comment by czosel** [comment]
@fkm It seems that this is still an issue. Can you take a look?

**Comment by fkm** [comment]
@JohnL17 Does work now?

**Comment by fkm** [comment]
Fixed
