### ISSUE TITLE
Table rendering: Make displayed columns configurable

### ISSUE THREAD

**Issue by czosel** [projectcaluma/ember-caluma#236]
It would be great if the displayed columns in a table were configurable in the form builder (currently we're always rendering the first 4 columns). For storage, I'd suggest using `meta` on the TableQuestion. The most basic implementation I can think of is just a static list of question slugs. This list could potentially run out-of-sync with the form backing the table, which something I wouldn't solve in a first version.

A more advanced version would allow for dynamic column contents, e.g. two field values joined together in one column (might be possible using JEXL). But that seems like something that we better leave out for the moment.

For the basic version, I'd expect a checkbox group with all the table's questions in the form builder UI.

/cc @fkm @kaldras @anehx

**Comment by anehx** [comment]
:+1:

**Comment by czosel** [comment]
Implemented in #237 
/cc @JohnL17
