### ISSUE TITLE
Limit search results in form builder

### ISSUE THREAD

**Issue by anehx** [projectcaluma/ember-caluma#251]
Currently, if we add a question to a form, we load all of the available answers per default. Since we have tons of available question in some projects we should limit this per default to e.g. 10 results. This should not be a problem since we offer a search functionality. We could also implement a "load more" button for users who don't really know what they want to add :wink:

**Comment by fkm** [comment]
Good point. I would suggest not showing any questions until a search query is entered.

**Comment by fkm** [comment]
How will it help to display an arbitrarily chosen subset of questions?

**Comment by czosel** [comment]
We'd just display the first 10 questions. For smaller forms, that might be really helpful already. I'd recommend displaying a "show more" link below the first 10 questions, though.

**Comment by fkm** [comment]
In the end I don't really care which way we go. But to make these 10 questions useful we'd need some way of weighing them to decide which ones to display first.

* Most used
* Newest additions
* ...

The reason I was advocating not fetching an initial list is to able to show a somewhat relevant list through user input. I don't really care about server load as this is not a visitor facing part of the application and thus should not generate the request volume that the public part of the projects do.

**Comment by anehx** [comment]
This was implemented with #1064
