### ISSUE TITLE
Flakey test in ember-form

### ISSUE THREAD

**Issue by Yelinz** [projectcaluma/ember-caluma#2514]
Sometimes fails, retry of test passes
```
not ok 29 Chrome 116.0 - [101 ms] - Integration | Component | cf-field/input/action-button: validates as configured
    ---
        actual: >
            
        expected: >
            validate
        stack: >
                at Assert.verifySteps (webpack://__ember_auto_import__/../../node_modules/.pnpm/qunit@2.19.4/node_modules/qunit/qunit/qunit.js?:283:51)
        negative: >
            false
        browser log: |
    ...
```
https://github.com/projectcaluma/ember-caluma/actions/runs/6170568375/job/16747149151
https://github.com/projectcaluma/ember-caluma/actions/runs/6183695072/job/16785971723

**Comment by derrabauke** [comment]
:heavy_plus_sign: [that](https://github.com/projectcaluma/ember-caluma/actions/runs/7252527626/job/19757227879?pr=2467#step:4:85)

**Comment by Yelinz** [comment]
Only fails on chrome, have never gotten it to fail on firefox.
Maybe we should just remove this test, as the functionality is already being tested multiple times in other tests. https://github.com/projectcaluma/ember-caluma/blob/ebcd822c65b8639f6449a702e74a8129f14f718d/packages/form/tests/integration/components/document-validity-test.js#L34-L54

Any opinion @anehx @derrabauke

**Comment by anehx** [comment]
@Yelinz yeah, let's remove it so our pipelines have meaning again..
