### ISSUE TITLE
Form: allow resetting of selected value in choice questions

### ISSUE THREAD

**Issue by czosel** [projectcaluma/ember-caluma#2542]
Currently, it is not possible to remove a previous selection of choice questions. Especially for optional choice questions this can be annoying, because there is no way to undo an accidental click. One way we could solve this is by adding a "Reset" button below the question, which could be displayed as a link (to be unobstrusive):

![image](https://github.com/projectcaluma/ember-caluma/assets/7962156/df4c97d7-1118-4f85-afdf-b9b74dee0fb1)

We should display the reset button only for optional questions, and only after a selection has been made (to be even less obstrusive).

**Comment by StephanH90** [comment]
has been implemented: https://github.com/projectcaluma/ember-caluma/pull/2549
