### ISSUE TITLE
Compatibility tests are not actually running

### ISSUE THREAD

**Issue by Yelinz** [projectcaluma/ember-caluma#2546]
https://github.com/projectcaluma/ember-caluma/actions/runs/6432558967/job/17467780251?pr=2530

No tests are executed from the whole compatibility matrix. In any action run which I inspected.

**Comment by anehx** [comment]
![image](https://github.com/projectcaluma/ember-caluma/assets/6150577/ac1da21c-c854-4c5e-8692-052c01a50bea)

This is a screenshot from the job you linked. What exactly is the problem?

**Comment by Yelinz** [comment]
yup exactly that, seems fixed with the pr
