### ISSUE TITLE
Wrong `field` reference in questions

### ISSUE THREAD

**Issue by fkm** [projectcaluma/ember-caluma#306]
It seems that the same field reference is passed to all questions. But this also includes the answer property on the field.

I'm not sure, where exactly this happens but to illustrate the problem here's a screenshot showing the relevant tree / values.

![Screenshot_20190604_152326](https://user-images.githubusercontent.com/100262/58882540-bccd2980-86dc-11e9-9587-01a387ad53db.png)

**Comment by anehx** [comment]
The new structure (#376) does not pass a `field` to the question - therefore this should be fixed.
