### ISSUE TITLE
Info fields in tables

### ISSUE THREAD

**Issue by czosel** [projectcaluma/ember-caluma#312]
When clicking on an info icon in a table modal, the info modal opens and closes the table modal automatically. Displaying the info modal on top of the table modal would solve the problem, but it's quite ugly and probably also not meant to be done with uk-modal. If we decide to give uk-drop another try, we have to figure out the sizing/formatting issues that lead us to using modals earlier.
/cc @fkm

**Comment by anehx** [comment]
I approve. We used modals because the info can be markdown and therefore quite uncontrollable, right?

**Comment by czosel** [comment]
We originally tried with uk-drop, but had a hard time adjusting it's size to

* fit lots of content (full width)
* looks good with not much content (not full width)

**Comment by anehx** [comment]
So maybe modal actually is the better choice?

**Comment by anehx** [comment]
I think drops are more for simple "twitter like" information texts. However, since we can have a lot more content, even markdown formatted, we should keep using modals..

**Comment by czosel** [comment]
Yeah, I agree. Any idea how to solve the "stacked modals" issue?

**Comment by anehx** [comment]
Already solved :wink:

**Comment by anehx** [comment]
I'll push the fix as soon as my laptop is alive again
