### ISSUE TITLE
Let babel config be the host apps problem

### ISSUE THREAD

**Issue by anehx** [projectcaluma/ember-caluma#341]
https://github.com/projectcaluma/ember-caluma/blob/144e81c5d9a5404a2d2f91604bc92424099e190c/index.js#L19-L26

I think we should remove this chunk of code in favor of explaining how to configure the host app the correct way. The babel config should be a concern of the host app, not the addon..

**Comment by anehx** [comment]
Actually, I'm not sure removing this is the way to go. Maybe we should just remove the decorators plugin (this is the default since v3.6+, we support the current LTS v3.8+)

**Comment by czosel** [comment]
Ok - whats the reason for the change of mind?

**Comment by anehx** [comment]
Adding plugins from an addon is a topic in the `ember-cli-babel`, therefore concidered good practice
