### ISSUE TITLE
Jexl dependency outdated?

### ISSUE THREAD

**Issue by fkm** [projectcaluma/ember-caluma#549]
Shouldn't Jexl v2.2.0+ be referenced here?
https://github.com/projectcaluma/ember-caluma/blob/ffbf840b5ba663cf08ae9aa6f3937053d7c41a4b/package.json#L60

We use `createExpression` here:
https://github.com/projectcaluma/ember-caluma/blob/84bbb2e73347a141f4a4613d07618faef0203867/addon/utils/jexl.js#L16

But, if I read the changelog correctly that was only introduced to Jexl in 2.2.0:
https://github.com/TomFrost/Jexl/blob/master/CHANGELOG.md#v220

**Comment by anehx** [comment]
`^2.1.1` is a version range which includes `2.2.0`. The `yarn.lock` file has the information which version is really referenced:

https://github.com/projectcaluma/ember-caluma/blob/ffbf840b5ba663cf08ae9aa6f3937053d7c41a4b/yarn.lock#L10452

If you have problems with an outdated jexl dependency in your project, try `yarn upgrade ember-caluma` - this will upgrade ember caluma _including_ it's dependencies..

**Comment by fkm** [comment]
Wouldn't it be more prudent to set the minimum required version in the package.json?

Instead of relying on some hack / workflow that people will first have to know.

**Comment by anehx** [comment]
Fair enough, PRs welcome..
