### ISSUE TITLE
SCSS compilation issue

### ISSUE THREAD

**Issue by ronny35** [projectcaluma/ember-caluma#572]
Hello,

When I build one Ember project with 'app.scss' contening these lines :
`@import "ember-uikit";`
`@import "ember-caluma";` 

This error appears :
`File to import not found or unreachable: ember-uikit/variables-theme`

I use `broccoli-sass` to compile this file. I do the same test with `ember-cli-sass` and it works correctly.

Thanks for your help.

**Comment by anehx** [comment]
Since this is an issue with `ember-uikit` not `ember-caluma` and there already exists [an issue tracking it](https://github.com/adfinis-sygroup/ember-uikit/issues/245) I'll close this.
