### ISSUE TITLE
ember-intl doesn't work with engines

### ISSUE THREAD

**Issue by Yelinz** [projectcaluma/ember-caluma#576]
ember-intl and engines are incompatible, the translations don't get applied when a different language than the default language is used. 

Maybe relevant issue and PR on ember-intl
https://github.com/ember-intl/ember-intl/issues/797
https://github.com/ember-intl/ember-intl/pull/846

**Comment by anehx** [comment]
That's not true anymore. Translations work perfectly in other languages.
