### ISSUE TITLE
Make meta editable like jexl

### ISSUE THREAD

**Issue by Yelinz** [projectcaluma/ember-caluma#578]
Add meta to the advanced options like isRequired and isHidden, so it is editable from the form builder.

This may cause problems thats why it should also be configurable if the meta field gets shown or not.

**Comment by czosel** [comment]
Interesting idea! Some questions:

* What are possible use cases for this?
* What kind of problems are you expecting?
* How would the editing UI look like? Key-value pairs with input fields, or full-blown JSON editing?

**Comment by Yelinz** [comment]
> What are possible use cases for this?

One potential use case would be for admins/ developers to edit the meta if something went wrong with the application and a wrong value got saved, which can't be changed due to errors.

> What kind of problems are you expecting?

Problems would happen when the application expects something in the meta and nothing or a wrong value is present because it was edited.
This shouldn't cause any problems with camac, but the surrounding application could be broken because of it.

> How would the editing UI look like?

For the editing UI I would suggest a textbox with meta JSON prettified.

**Comment by czosel** [comment]
I really like the idea! This also allows building custom UI features and still make them configurable by admins without extending the form builder. I think a textarea with the prettified JSON would be great for developers, but maybe not so much for non-technical users. I’d be ok with starting simple though, it’s always possible to add some kind of editing UI for it in the future.
