### ISSUE TITLE
Form builder: Add namespace for slugs

### ISSUE THREAD

**Issue by kaldras** [projectcaluma/ember-caluma#60]
While initializing the form builder it should be possible to define a namespace which is then added to each slug that is created in this session. For example:

`namespace: "foobar"`

Question slug of question "blubber" should be: `foobar-blubber`

It would be nice to see the namespace as non-editable text before the slug field, so the user knows how the final slug looks.

**Comment by fkm** [comment]
I have yet to find a way to pass the user/group (i.e. session) to the addon.

I could use a dependency injection to pass the OpenID session to the addon and the application configuration to define what part of the session should be used (eg. via Jexl string). The problem with the dependency is that it will fall flat when the host application doesn't provide a session for injection.

**Comment by fkm** [comment]
Maybe via a [custom authenticator](https://github.com/simplabs/ember-simple-auth/tree/master#implementing-a-custom-authenticator). I will have a look.

**Comment by fkm** [comment]
After looking at everything I could think of, I currently only see the solution in attaching the namespace to `window`. But I'm open for suggestions.
